url: http://www.maisasolutions.com/
baseurl: ""

# Site settings
pic: logo
email: contact@maisasolutions.com
title: "Maisasolutions | Web and mobile development services company"
description: "MaisaSolutions is a web and mobile development services company. We build awesome things for the web & mobile. We’re creators, designers, engineers, educators and problem solvers. We provides Agile Ruby on Rails Development and Consulting."
keywords: "Ruby on Rails Developers, Ruby on Rails development companies, Ruby on rails companies in india, RoR team, Agile Ruby on Rails Development & Consulting, RoR development and consulting, Ruby on Rails web development, Ruby on Rails development companies, Rails web services, Ruby on Rails Web Development, Ruby on Rails Development team, software outsourcing solutions, mobile applications development, iOS Developers, Android Developers, iOS and Android development companies, JavaScript, HTML5, CSS3, Ruby on Rails, Angular.js, Node.js, Java, NoSQL Databases"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: C52128 #fed136
  secondary: C52128 #fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Pradeep Benjaram
  pic: 1
  position: M.D. (Maisa™ group)
  description: Serial entrepreneur. True leader with an exceptional ability to put together right teams develivering innovative results. Pradeep's vision for outstanding customer experience helps us in defining our core values and day-to-day operational success.

- name: Chris Morocco
  pic: 2
  position: Partner & Advisory Member
  descrption: Coach. Enterprenuer.

- name: Frank Newlands, MD
  pic: 3
  position: Advisory Member
  descrption: Doctor by profession. Dad of 3 by person. Helps us choose right customer for win-2-win ground. When not working, you can spot him fishing across the globe.

- name: Niveditha Reddy
  pic: 4
  position:
  description: Having worked in IT for 12+yrs, Nivi, brings unique skills to our hiring department. Her ability to understand what motivates people, helping us source right talent from zillion choices most effectively.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
   - title: linkedin
     url: https://www.linkedin.com/company/maisa-solutions
   - title: twitter
     url: https://twitter.com/maisasolutions
   - title: google-plus
     url: https://plus.google.com/+Maisasolutions/posts
   - title: facebook
     url: https://www.facebook.com/MaisaSolutions

# Postal address (add as many lines as necessary)
address:
  - line: 555 California Street, Suite 4925
  - line: San Francisco, CA 94104


# Build settings
markdown: kramdown
permalink: /:title.html

permalink: /404.html

# Handling Reading
include:      ['.htaccess']
