url: http://www.maisasolutions.com/
baseurl: ""

# Site settings
pic: logo
email: contact@maisasolutions.com
title: "Maisasolutions | Web and mobile development services company"
description: "MaisaSolutions is a web and mobile development services company. We build awesome things for the web & mobile. We’re creators, designers, engineers, educators and problem solvers. We provides Agile Ruby on Rails Development and Consulting."
keywords: "Ruby on Rails Developers, Ruby on Rails development companies, Ruby on rails companies in india, RoR team, Agile Ruby on Rails Development & Consulting, RoR development and consulting, Ruby on Rails web development, Ruby on Rails development companies, Rails web services, Ruby on Rails Web Development, Ruby on Rails Development team, software outsourcing solutions, mobile applications development, iOS Developers, Android Developers, iOS and Android development companies, JavaScript, HTML5, CSS3, Ruby on Rails, Angular.js, Node.js, Java, NoSQL Databases"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: C52128 #fed136
  secondary: C52128 #fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Pradeep Benjaram
  pic: 1
  position: Founder, Managing Director
  description: True leader. Serial entrepreneur. Pradeep's vision for great customer experience helps us in defining our core values.

- name: Niveditha Reddy
  pic: 2
  position: Director of Human Resources
  description: Having worked as a software engineer for about 10years, Nivi, brings unique skills to our hiring department. Her engineering plus human resources skills helped us to choose right engineers from zillion other choices most effectively.

- name: Prasanna Patil
  pic: 3
  position: Director of Operations(USA)
  description: Prasanna recipient of Graduate Citation holds a Masters degree from CUNY and is also PMP certified. Prasanna brings over a decade of management, business transformation and information technology consulting experience in delegating and deploying large global enterprise applications. In addition to overseeing the company’s US operations on a daily basis, Prasanna is passionately involved in client facing, ERP solution architecture and IT project management/implementations activities. Prasanna in paramount positions has consulted for several large scale global fortunes 500 clients.

- name: Dave Arora
  pic: 4
  position: Director of Business Development
  description: Dave is responsible forglobal corporate growth initiatives including strategy, mergers, acquisitions, strategic ventures and alliances. Dave is an entrepreneur, creator and coach in essence. Professionally, he has a rich 25 years of business experience from North America and Asia in different roles including Business Development, Regional Marketing and General Management to integrating new talent and technology to offer scalable, secured & easily deployable solutions for Cloud Computing, Big Data Initiative, Web & Mobile Applications Development and solve the most challenging Data Storage & Processing requirements. Prior to joining MAISA, Dave was helping Veteran Owned Small Businesses on US east coast to win IT Hardware, Software and Services requirements of US Department of Defense via Federal Contracting Systems vehicle. <br> Dave received his Master’s degree in Business Administration specialization in Information Systems from India.


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
   - title: facebook
     url: https://www.facebook.com/MaisaSolutions
   - title: twitter
     url: https://twitter.com/maisasolutions
   - title: google-plus
     url: https://plus.google.com/+Maisasolutions/posts
   - title: youtube
     url: https://www.youtube.com/watch?v=v5GpjKcUrF8&amp;feature=youtu.be
   - title: linkedin
     url: https://www.linkedin.com/company/maisa-solutions

# Postal address (add as many lines as necessary)
address:
  - line: 555 California Street, Suite 4925
  - line: San Francisco, CA 94104


# Build settings
markdown: kramdown
permalink: /:title.html

permalink: /404.html

# Handling Reading
include:      ['.htaccess']
