url: http://www.maisasolutions.com/
baseurl: ""

# Site settings
title: Web Development Services | Mobile Application Developers
pic: logo
email: your-email@domain.com
description: "Web and mobile development services. We offer ios native application, mobile apps, web development with ruby on rails, java, cloud computing and many more."
keywords: "ios mobile app development, web development services, mobile apps development, ruby on rails developers, mobile development services, mobile apps cloud computing, mobile application development, java web development services, ios development services, iOS Native Application Development"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: C52128 #fed136
  secondary: C52128 #fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Pradeep Benjaram
  pic: 1
  position: Founder & M.D.
  description: 'Pradeep, with over 15years of experience in delivering high quality output across different business sectors'

- name: Niveditha Reddy
  pic: 2
  position: Director of Human Resources
  description: 'Nivi, with over 10years of problem solving experience, plays a key role to the company for both internal & external communication. Extremely detailed and ability to bridge gap between engineering & management puts her in such a key role for us.'

- name: Prasanna Patil
  pic: 3
  position: Director of U.S. Ops
  description: 'Prasanna recipient of Graduate Citation holds a Masters degree from CUNY and is also PMP certified. Prasanna brings over a decade of management, business transformation and information technology consulting experience in delegating and deploying large global enterprise applications. In addition to overseeing the company’s US operations on a daily basis, Prasanna is passionately involved in client facing, ERP solution architecture and IT project management/implementations activities. Prasanna in paramount positions has consulted for several large scale global fortunes 500 clients.'

- name: Dave Arora
  pic: 4
  position: Director of Business Development
  description: 'Dave Arora is MAISA’s Corporate Director of Business Development Officer. He is responsible for MAISA’s global corporate growth initiatives including strategy, mergers, acquisitions, strategic ventures and alliances. Dave is an Entrepreneur, Creator and Coach in essence. Professionally, he has a rich 25 years of business experience from North America and Asia in different roles including Business Development, Regional Marketing and General Management to integrating new talent and technology to offer scalable, secured & easily deployable solutions for Cloud Computing, Big Data Initiative, Web & Mobile Applications Development and solve the most challenging Data Storage & Processing requirements. Prior to joining MAISA, Dave was helping Veteran Owned Small Businesses on US east coast to win IT Hardware, Software and Services requirements of US Department of Defense via Federal Contracting Systems vehicle. <br> Dave received his Master’s degree in Business Administration specialization in Information Systems from India.'


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
   - title: facebook
     url: https://www.facebook.com/MaisaSolutions
   - title: twitter
     url: https://twitter.com/maisasolutions
   - title: google-plus
     url: https://plus.google.com/+Maisasolutions/posts
   - title: youtube
     url: https://www.youtube.com/watch?v=v5GpjKcUrF8&amp;feature=youtu.be
   - title: linkedin
     url: https://www.linkedin.com/company/maisa-solutions

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills , CA 90210


# Build settings
markdown: kramdown
permalink: /:title.html

# Handling Reading
include:      ['.htaccess']
